<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>Chessington.UI</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Chessington.GameEngine\Chessington.GameEngine.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Icons\*.ico" />
    <Resource Include="Icons\Black B.ico" />
    <Resource Include="Icons\Black K.ico" />
    <Resource Include="Icons\Black N.ico" />
    <Resource Include="Icons\Black P.ico" />
    <Resource Include="Icons\Black Q.ico" />
    <Resource Include="Icons\Black R.ico" />
    <Resource Include="Icons\White B.ico" />
    <Resource Include="Icons\White K.ico" />
    <Resource Include="Icons\White N.ico" />
    <Resource Include="Icons\White P.ico" />
    <Resource Include="Icons\White Q.ico" />
    <Resource Include="Icons\White R.ico" />
  </ItemGroup>
</Project>
